### ISSUE TITLE
VLSub stopped working

### ISSUE THREAD

**Issue by 2ge** [exebetche/vlsub#143]
Hi,

opensubtitles made some update on API (gzip compression support, removed pretty print), VLSub for some reason stopped working and is freezing. What is the cause ?

https://forum.opensubtitles.org/viewtopic.php?f=8&t=15823&p=35855#p35855

**Comment by JulesKozolinsky** [comment]
hello, same problem here on macOS : search (by hash or name) is freezing.

**Comment by exebetche** [comment]
Hi,
One reason I've seen so far is not listed in the changes: the "Transfer-Encoding" is now set to "chunked" which I've never bothered to support. That might not be the only problem with this changes but that would be the the first to fix.

**Comment by DuboisJoris** [comment]
Same problem :-)

**Comment by Dashue** [comment]
+1

**Comment by CoLdAs1cE** [comment]
+1

**Comment by Dashue** [comment]
Realized just now, that it worked just by leaving it for a bit. Vlc tells me its not responding  but waiting worked.

**Comment by Infinitay** [comment]
having the same issue, everything is uptodate as well

**Comment by andrejunges** [comment]
+1

**Comment by opensubtitles** [comment]
Hello everybody. It is caused by CloudFlare. We got some communication with them, and they are adding "Transfer-Encoding:chunked" when there is http 1.1 response from server. More here
https://support.cloudflare.com/hc/en-us/articles/200168386-Why-is-my-dynamic-content-being-sent-with-chunked-encoding-

We didn't use CF until now - it saves as a lot of bandwidth, they make great job (compressing requests between client and server, saving more than 50% of traffic)

The problem is, there is no way how to force HTTP 1.0 response to HTTP 1.1 requests without hacking of webserver source codes. 

That means only way how to fix this is install new version of VLSub, which is not yet released.

@exebetche I tried VLSub and it hangs because of Transfer-Encoding:chunked

**Comment by exebetche** [comment]
@opensubtitles I know about the transfer encoding. I started to work on a fix but I doesn't work yet and sadly I won't be able to finish it because I will be away for a week.

Thank you

Here is a test I've done so far in case someone want to give it a try:

`function http_req(host, port, request)
  local fd = vlc.net.connect_tcp(host, port)
  if not fd then return false end
  local pollfds = {}

  pollfds[fd] = vlc.net.POLLIN
  vlc.net.send(fd, request)
  vlc.net.poll(pollfds)

  local chunk = vlc.net.recv(fd, 2048)
  local response = ""
  local headerStr, header, body
  local contentLength, status
  local pct = 0
  local chunked = false
  --~ vlc.msg.err("chunk0", chunk)

  while chunk do
  --~ vlc.msg.err("chunk", chunk)
  --~ vlc.msg.err("response", response)
	if chunked then
		if chunk_to_go > 0 then
			chunk_content = chunk:sub(0, chunk_to_go)
			response = response..chunk_content
			--~ vlc.msg.err("chunk_content", chunk_content)
			chunk = chunk:sub(chunk_to_go)
		end
		chunk_len = chunk:len()
		
		vlc.msg.err("chunk_len", chunk_len)
		
		if chunk_len > 0 then
			chunk_size_hex, chunk_content = chunk:match("(%x+)\r?\n(.*)")
			chunk_content_len = chunk_content:len()
			chunk_size = tonumber(chunk_size_hex,16)
			chunk_to_go = chunk_size-chunk_content_len
			vlc.msg.err("chunk_size", chunk_size)
			vlc.msg.err("chunk_size", chunk_size)
			vlc.msg.err("chunk_content_len", chunk_content_len)
			vlc.msg.err("chunk_to_go", chunk_to_go)
			response = response..chunk_content
		else
		
				local tmpFile = io.open("out.txt", "wb")
				tmpFile:write(response)
				tmpFile:flush()
				--~ tmpFile:close()
				tmpFile = nil
			break
		end
			
	else
		response = response..chunk
	end

    if not header then
        headerStr, body = response:match("(.-\r?\n)\r?\n(.*)")
        if headerStr then
			--~ vlc.msg.err("headerStr", headerStr)
			--~ vlc.msg.err("body", body)
            response = body
            header = parse_header(headerStr)
            TransferEncoding = trim(header["Transfer-Encoding"])
            --~ vlc.msg.err("TransferEncoding", "#"..TransferEncoding.."#")
            contentLength = tonumber(header["Content-Length"])
            status = tonumber(header["statuscode"])
            
            if TransferEncoding=="chunked" then
				chunked = true
				
				
				chunk_size_hex, chunk_content = body:match("(%x+)\r?\n(.*)")
				chunk_size = tonumber(chunk_size_hex,16)
				chunk_content_len = chunk_content:len()
				chunk_to_go = chunk_size-chunk_content_len
				
				response = chunk_content
				--~ vlc.msg.err("chunk_size", chunk_size)
				--~ vlc.msg.err("chunk_content_len", chunk_content_len)
				--~ vlc.msg.err("chunk_to_go", chunk_to_go)
            end
        end
    end

	if contentLength then
		vlc.msg.err("contentLength", contentLength)
		bodyLenght = #response
		pct = bodyLenght / contentLength * 100
		setMessage(openSub.actionLabel..": "..progressBarContent(pct))
		if bodyLenght >= contentLength then
			break
		end
	end

    vlc.net.poll(pollfds)
    chunk = vlc.net.recv(fd, 1024)
  end

  vlc.net.close(fd)

  if status == 301
  and header["Location"] then
    local host, path = parse_url(trim(header["Location"]))
    request = request
    :gsub("^([^%s]+ )([^%s]+)", "%1"..path)
    :gsub("(Host: )([^\n]*)", "%1"..host)

    return http_req(host, port, request)
  end

  return status, response
end`

**Comment by opensubtitles** [comment]
@exebetche I am no LUA programmer, but maybe these URLs will help with handling chunked encoding:
https://github.com/pintsized/lua-resty-http
https://gist.github.com/daurnimator/4d85c92da22c1866a744
https://github.com/aperezdc/luabot/blob/master/net/http/parser.lua

**Comment by opensubtitles** [comment]
for users of VLSub: in meantime you can add to your **hosts** file:
```
92.240.234.122  api.opensubtitles.org
```

this should fix it. Don't forget to delete this entry once new VLSub is released

**Comment by SitramSoft** [comment]
Thanks for the intermediary fix! I can finally download subtitles to my movies and tv shows.

**Comment by sameermw** [comment]
+1 and fixed with this entry 

> 92.240.234.122  api.opensubtitles.org

**Comment by alextsak88** [comment]
hello 

where do i add this and since i dont have a hosts file in vlc  what can i do?

**Comment by SitramSoft** [comment]
C:\Windows\System32\Drivers\etc

Edit it with notepad and add the text "92.240.234.122  api.opensubtitles.org"

**Comment by opensubtitles** [comment]
time to use google. Search for "hosts file". It is part of your OS, not VLC.

https://en.wikipedia.org/wiki/Hosts_(file)

**Comment by alextsak88** [comment]
damn that simple huh.? 
thanks much appreciated 👍

**Comment by guilhermelawless** [comment]
Thank you for the temporary fix. Now to remember to delete this when an updates comes.

**Comment by waptik** [comment]
@opensubtitles thanks for the temp fix with the hosts file. +1 for that

**Comment by mobradovic** [comment]
> in meantime you can add to your hosts file:
> 92.240.234.122  api.opensubtitles.org

Thanks man, you rock!

**Comment by didaski** [comment]
I tried to use the fix, but it didn't work for me.
I put the string after "broadcasthost". I found another "hosts-origin" file in the "etc" folder. 
Should I delete that? Any hint?

**Comment by lamaresh** [comment]
Maybe this will not be the most elegant way... but if you just comment line 1938 it starts working again.
I mean the second vlc.net.poll(pollfds) in http_req function

**Comment by AlanSP1** [comment]
You did something wrong. What, it's hard to tell. Just find hosts file of your windows at add at the very end aforementioned line. This will work. You don't even need to restart windows or anything.

**Comment by moshpirit** [comment]
Is for linux adding it to `/etc/hosts`?

**Comment by dieuwedeboer** [comment]
Can confirm that adding the IP to `/etc/hosts` works.

**Comment by gazialankus** [comment]
@opensubtitles please update us here and let us know when we should update and remove this hosts entry.

**Comment by didaski** [comment]
Could it be that it doesn't work for mac?


Il 01/11/16 02:13, Alan ha scritto:

**Comment by jairodsl** [comment]
The following answer from VLC forums worked for me https://forum.videolan.org/viewtopic.php?t=136182

Re: Problem with downloading subs
Postby Rémi Denis-Courmont » 29 Oct 2016 14:30

OpenSubtitles.org has apparently updated their servers. That uncovered latent bugs in the very dumb HTTP support of the VLSub extension.

To work around the problem (you might need administrator privileges):
Go to the VLC installation directory.
Look for the file named lua/extensions/VLSub.luac.
Open that file in a binary or hexadecimal editor. (DO NOT USE a text editor.)
Look for the character sequence "HTTP/1.1" (without quotes).
Replace the last one by a zero: "HTTP/1.0".
Repeat the procedure; there should be a second occurence in the file.
Save the file.
(Re)start VLC.

**Comment by guilhermelawless** [comment]
Can't find those files in a Linux .deb installation, but should indeed work
for Windows.

**Comment by didaski** [comment]
@jairodsl  thanks a lot, this worked for me!

**Comment by davidalbertonogueira** [comment]
@jairodsl, instead of editing that luac, I installed the vlsub.lua file from this repository (source code, not binary) and edited that one.

**Comment by SuRuPu** [comment]
The hosts-file and .luac editing did nothing, but .lua-file edit finally solved the problem. Thanks for the help, specially @davidalbertonogueira !

**Comment by ovyhlidal** [comment]
@jairodsl Nice work man :) Your fix work nicely!

**Comment by varenc** [comment]
I put @jairodsl's fix in a pull request.   Not sure if it'll be accepted since it is indeed a bit hacky, but if you'd just like something working now you can pull my fix just by doing this: 
`git clone -b fix-vlsub https://github.com/varenc/vlsub.git`

**Comment by Jackcrn** [comment]
Thank you @jairodsl fantastic!! Works perfect! 
Really appreciated.

For those that don't know what binary progam can use, I use Frhed available on sourceforge http://frhed.sourceforge.net/en/ 

Cheers!

**Comment by jairoserranosp** [comment]
Thx, but I am not the author of the fix, it is Rémi Denis-Courmont as I wrote.

**Comment by Jackcrn** [comment]
> @jairoserranosp 
Thx, but I am not the author of the fix, it is Rémi Denis-Courmont as I wrote.
Ok, I got it. Thank you.
The situation is that I can't read the Vlan forum, nothing works, the forum appears like without style sheet, and any link works. That's why I appreciated your info :) 
[https://pbs.twimg.com/media/CwWJJ3nWgAAXLh6.jpg](Watch what I get of the Vlan forum) 

Regards

**Comment by vhristev** [comment]
Use Vim as a hex editor:
Open the file in Vim.
Run the command
:% ! xxd
Edit.
Once done, run
:% ! xxd -r
Save.

You can POST and GET HTTP request . 
https://i.imgsafe.org/c66939655f.jpg
https://i.imgsafe.org/c66922b855.jpg

**Comment by exebetche** [comment]
I think that's fixed with the last update (version 0.10.0).

**Comment by bilak** [comment]
sorry for commenting in closed issue, but how to install version 0.10.0? I've coppied [this file](https://dl.opendesktop.org/api/files/download/id/1478360358/vlsub.lua) to `/Applications/VLC.app/Contents/MacOS/share/lua/extensions`, removed old VLSub.luac and when started VLC (version 2.4) no vlsub extension is available.

**Comment by exebetche** [comment]
@bilak no problem, make sure that the file as the right extension, in a terminal try this command:
`ls /Applications/VLC.app/Contents/MacOS/share/lua/extensions`
--> You should see the file vlsub.lua in the output.

If it's there, please give me your VLC debug log as explained here:
https://github.com/exebetche/vlsub/wiki/Troubleshooting

**Comment by bilak** [comment]
@exebetche forget about it...it was my fault. I downloaded bad file :D. When using debug I just realised that. It works! thanks

**Comment by exebetche** [comment]
@bilak Ok, cool.

**Comment by stonemirror** [comment]
Yup, adding the line

```
92.240.234.122  api.opensubtitles.org
```

to the /etc/hosts file allows VLSubs 0.9.13 to function again on OS X Sierra (v10.12.1)...

**Comment by TheIronRose** [comment]
So I've added the above fixes (hex editing the .luac file, adding the api.opensubtitles.org IP to my hosts file), and I've installed the new version of VLSub. However, I'm now getting a new error from vlsub - 401 unauthorized access (200), which means the server is denying the request. Any assistance in this regard?

On windows 10 x64.

**Comment by opensubtitles** [comment]
probably your IP is suspicious, you have to be logged in to use API. Click Show Config in VLSub and fill your opensubtitles username and password.

**Comment by giacomocerquone** [comment]
Just for curiosity, the fix with the hosts file works because that is the old version of the API that does not use cloudflare?

**Comment by opensubtitles** [comment]
well, the one working fix for now is to download older version of VLSub 0.10.0, and then change hosts file.

**Comment by giacomocerquone** [comment]
yeah I understood... I was asking if the reason was the one I wrote above (y)

**Comment by avk2** [comment]
4th February of 2017, still not fixed...

**Comment by AlanSP1** [comment]
It was fixed long time ago, with version 10.0. You can download it here: https://addons.videolan.org/p/1154045/

**Comment by varenc** [comment]
you should probably update the releases: https://github.com/exebetche/vlsub/releases
or just delete that release completely as it's broken

**Comment by svenboogaart** [comment]
+1

**Comment by avk2** [comment]
VLC player still have the broken version (at least the debian package)

**Comment by zsoobhan** [comment]
Still a valid fix on `VLC Version 2.2.5.1` with `VLsub 0.9.10` running on `MacOS 10.12.5`
